<?php

/**
*
* Replace the og:image content generated by Yoast SEO
*
* If $_GET['bedev-share-id'] is set, replace the og:image with the image being shared.
*
* @since 0.0.1
*
* @param str $content the additional image to montage
* @return str url for the new og:image
*
**/

function bedev_replace_og_image( $content ) {
	
	if( isset( $_GET['bedev-share-id'] ) ) {
		
		$args = array( 
			'post_type' => 'attachment',
			'meta_value' => $_GET['bedev-share-id'],
		);
		
		$image = get_posts( $args );
		
		$image_url = wp_get_attachment_url( $image[0]->ID );
		return $image_url;
		
	}
	
	return $content;
	
}

add_filter( 'wpseo_og_og_image' , 'bedev_replace_og_image' );
add_filter( 'wpseo_twitter_image' , 'bedev_replace_og_image' );


/**
*
* Replace the og:url and canonical url content generated by Yoast SEO
*
* If $_GET['bedev-share-id'] is set, replace the og:url and canconical with the image being shared.
*
* @since 0.0.1
*
* @param str $url url of the current page with query string
* @return str url of the current page with query string
*
**/

function bedev_replace_canonical( $url ) {
	
	if( isset( $_GET['bedev-share-id'] ) ) {
		
		//get the image class
		$imagick_options = new bedev_imagemagick_options;
		
		//get the front end path
		$path = $imagick_options->front_end_path;
		
		return $path . '?bedev-share-id=' . $_GET['bedev-share-id'];
		
	}
	
	return $url;
	
}

add_filter( 'wpseo_og_og_url' , 'bedev_replace_canonical' );
add_filter( 'wpseo_canonical' , 'bedev_replace_canonical' );


/**
*
* Add additioanl og:image:width and og:image height attributes
*
* NB. this is hooked to 'wpseo_opengraph' action from Yoast WPSEO
*
* @since 0.0.1
*
**/

function bedev_add_og_image_atts() {
	
	if( isset( $_GET['bedev-share-id'] ) ) {
		
		//get the image class
		$imagick_options = new bedev_imagemagick_options;
		
		//get the facebook details
		//later to be replaced with an option sent in the ajax request
		$imagic_details = $imagick_options->get_social_network_info( 'facebook' );
		
		//get the montage dimensions
		$imagick_dimensions = $imagic_details['image_sizes'];

		ob_start(); ?>

		<meta property="og:image:width" content="<?php echo $imagick_dimensions['width'] ?>">
		<meta property="og:image:height" content="<?php echo $imagick_dimensions['height'] ?>">

		<?php
		$html = ob_get_contents();
		if( $html ) ob_end_clean();
		echo $html;
		
	}

}

add_action( 'wpseo_opengraph' , 'bedev_add_og_image_atts' );


/**
*
* Edit the description added by Yoast SEO
*
* NB. this is hooked to 'wpseo_opengraph' action from Yoast WPSEO
*
* @since 0.0.1
*
**/

function bedev_edit_description_description( $description ) {
	
	if( isset( $_GET['bedev-share-id'] ) ) {
		
		//get the image class
		$imagick_options = new bedev_imagemagick_options;
		
		//get the facebook details
		//later to be replaced with an option sent in the ajax request
		$imagic_details = $imagick_options->get_social_network_info( 'facebook' );
		
		//get the link share description
		$imagick_description = $imagick_options->link_description;
		
		return $imagick_description;
		
	}
	
}

add_filter( 'wpseo_opengraph_desc' , 'bedev_edit_description_description' );
add_filter( 'wpseo_twitter_description' , 'bedev_edit_description_description' );